[package]
name = "syd"
version = "0.1.0"
edition = "2021"

[dependencies]
simple-expand-tilde = "0.4.0"
git2 = "0.18.1"
toml = "0.8.10"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"